/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppInput: typeof import('./src/components/app/AppInput.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonComponent: typeof import('./src/components/shared/ButtonComponent.vue')['default']
    Dashboard: typeof import('./src/components/chat/dashboard/Dashboard.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IsIcon: typeof import('./src/components/icon/IsIcon.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinnerComponent: typeof import('./src/components/shared/SpinnerComponent.vue')['default']
  }
}
